//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Services.PatientManagerServices.QueryProcessorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.PatientManagerServices.QueryProcessorService.PatientManagerQueryProcesso" +
        "r")]
    public interface PatientManagerQueryProcessor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PatientManagerQueryProcessor/Submit", ReplyAction="http://tempuri.org/PatientManagerQueryProcessor/SubmitResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ValueObjects.Wcf.MyValidator), Action="http://tempuri.org/PatientManagerQueryProcessor/SubmitMyValidatorFault", Name="MyValidator", Namespace="http://schemas.datacontract.org/2004/07/ValueObjects.Wcf")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PatientManager.Contract.Queries.FindPatientsBySearchTextQuery))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PatientManager.Contract.Queries.GetAllPatientsQuery))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PatientManager.Contract.Queries.GetAllPatientVisitsQuery))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PatientManager.Contract.Queries.GetContactInfoByPatientQuery))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PatientManager.Contract.Queries.GetHealthIdByPatientQuery))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PatientManager.Contract.Queries.GetPatientVisitByIdQuery))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PatientManager.Contract.Queries.GetPatientByIdQuery))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PatientManager.Contract.Queries.GetPatientVisitsByPatientQuery))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PatientManager.Contract.Dto.PatientDto[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PatientManager.Contract.Dto.PatientDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PatientManager.Contract.Dto.PatientVisitDto[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PatientManager.Contract.Dto.PatientVisitDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PatientManager.Contract.Dto.ContactInfoDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PatientManager.Contract.Dto.HealthIdentificationDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ValueObjects.Health.GenderType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ValueObjects.Health.Healthcard))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ValueObjects.ContactInformation.Address))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ValueObjects.ContactInformation.PhoneNumber))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ValueObjects.Wcf.MyValidator))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ValueObjects.Wcf.MyValidationFailure[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ValueObjects.Wcf.MyValidationFailure))]
        object Submit(object query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PatientManagerQueryProcessor/Submit", ReplyAction="http://tempuri.org/PatientManagerQueryProcessor/SubmitResponse")]
        System.Threading.Tasks.Task<object> SubmitAsync(object query);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PatientManagerQueryProcessorChannel : Infrastructure.Services.PatientManagerServices.QueryProcessorService.PatientManagerQueryProcessor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PatientManagerQueryProcessorClient : System.ServiceModel.ClientBase<Infrastructure.Services.PatientManagerServices.QueryProcessorService.PatientManagerQueryProcessor>, Infrastructure.Services.PatientManagerServices.QueryProcessorService.PatientManagerQueryProcessor {
        
        public PatientManagerQueryProcessorClient() {
        }
        
        public PatientManagerQueryProcessorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PatientManagerQueryProcessorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PatientManagerQueryProcessorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PatientManagerQueryProcessorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public object Submit(object query) {
            return base.Channel.Submit(query);
        }
        
        public System.Threading.Tasks.Task<object> SubmitAsync(object query) {
            return base.Channel.SubmitAsync(query);
        }
    }
}
